=== Khmelov/JD2017-09-20/src/by/it/mustaphin/jd02_07/xsd/Tickets.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://by.it.mustaphin/Tickets"
        xmlns:tns="http://by.it.mustaphin/Tickets"
        elementFormDefault="qualified">
    <element name="Tickets">
        <complexType>
            <sequence>
                <element name="Order" type="string"/>
                <element name="Header" type="tns:Header" minOccurs="1" maxOccurs="2"/>
                <element name="Ticket" type="tns:Ticket" minOccurs="1" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Header">
        <sequence>
            <element name="HeaderNumber" type="int"/>
            <element name="HeaderText" type="string"/>
        </sequence>
    </complexType>
    <complexType name="Ticket">
        <sequence>
            <element name="TicketNumber" type="string"/>
            <element name="Desc" type="string"/>
            <element name="Image" type="anyURI"/>
            <element name="Question" type="string"/>
            <element name="Answers" type="tns:Answers"/>
        </sequence>
    </complexType>
    <complexType name="Answers">
        <sequence>
            <element name="Answer" minOccurs="1" maxOccurs="4" type="tns:Answer"/>
        </sequence>
    </complexType>
    <complexType name="Answer">
        <sequence>
            <element name="AnswerNumber" type="int"/>
            <element name="Text" type="string"/>
        </sequence>
    </complexType>

</schema>

=== Khmelov/JD2017-09-20/src/by/it/mustaphin/jd02_07/xsd/Tickets.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Tickets xmlns="http://by.it.mustaphin/Tickets"
         xsi:schemaLocation="http://by.it.mustaphin/Tickets Tickets.xsd"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>
    <Order>
        W=44
    </Order>
    <Header>
        <HeaderNumber>
            1
        </HeaderNumber>
        <HeaderText>
            Инструкция о порядке проведения обязательных медицинских осмотров работающих,
            (Утв. пост. Министерства здравоохранения РБ от 28 апреля 2010 № 47)
        </HeaderText>
    </Header>
    <Header>
        <HeaderNumber>
            2
        </HeaderNumber>
        <HeaderText>
            Правила по охране труда в организациях здравоохранения.
            (Утв. пост. Министерства здравоохранения Республики Беларусь 10.06.2009 №64)
        </HeaderText>
    </Header>
    <Ticket>
        <TicketNumber>
            N01
        </TicketNumber>
        <Desc>
            (Л1 п.1.)
        </Desc>
        <Image>
            medos.wmf
        </Image>
        <Question>
            Что устанавливает Инструкция о порядке проведения обязательных медицинских
            осмотров работающих?
        </Question>
        <Answers>
            <Answer>
                <AnswerNumber>
                    1
                </AnswerNumber>
                <Text>
                    Порядок проведения обязательных медицинских
                    осмотров лиц, поступающих на работу, а также работающих,
                    занятых на работах с вредными и (или) опасными условиями
                    труда или на работах, для выполнения которых есть
                    необходимость в профессиональном отборе.
                </Text>
            </Answer>
            <Answer>
                <AnswerNumber>
                    2
                </AnswerNumber>
                <Text>
                    Порядок проведения предрейсовых медицинских
                    осмотров водителей автотранспорта.
                </Text>
            </Answer>
            <Answer>
                <AnswerNumber>
                    3
                </AnswerNumber>
                <Text>
                    Порядок проведения медицинского освидетельствования
                    работников в случае подозрения в употреблении алкоголя,
                    наркотических и токсикологических средств.
                </Text>
            </Answer>
            <Answer>
                <AnswerNumber>
                    4
                </AnswerNumber>
                <Text>
                    Все, что указано в других вариантах ответа.
                </Text>
            </Answer>
        </Answers>
    </Ticket>
    <Ticket>
        <TicketNumber>
            N02
        </TicketNumber>
        <Desc>
            (Л1 п.1.)
        </Desc>
        <Image>
            medos1.wmf
        </Image>
        <Question>
            Какие существуют виды обязательных медицинских
            осмотров работающих?
        </Question>
        <Answers>
            <Answer>
                <AnswerNumber>
                    1
                </AnswerNumber>
                <Text>
                    Предварительные (при поступлении на работу), периодические (в течении
                    трудовой деятельности) и внеочередные.
                </Text>
            </Answer>
            <Answer>
                <AnswerNumber>
                    2
                </AnswerNumber>
                <Text>
                    Предварительные (при поступлении на работу), ежегодные (в течении трудовой
                    деятельности).
                </Text>
            </Answer>
            <Answer>
                <AnswerNumber>
                    3
                </AnswerNumber>
                <Text>
                    Предварительные (при поступлении на работу), периодические (1 раз в 2
                    года) и предрейсовые.
                </Text>
            </Answer>
            <Answer>
                <AnswerNumber>
                    4
                </AnswerNumber>
                <Text>
                    Предварительные (при поступлении на работу), внеочередные (при ухудшении
                    состояния здоровья) и предрейсовые.
                </Text>
            </Answer>
        </Answers>
    </Ticket>
</Tickets>
